In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/news.csv')

In [ ]:
df.head()

Unnamed: 0                                              title  \
0        8476                       You Can Smell Hillary’s Fear   
1       10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2        3608        Kerry to go to Paris in gesture of sympathy   
3       10142  Bernie supporters on Twitter erupt in anger ag...   
4         875   The Battle of New York: Why This Primary Matters   

                                                text label  
0  Daniel Greenfield, a Shillman Journalism Fello...  FAKE  
1  Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE  
2  U.S. Secretary of State John F. Kerry said Mon...  REAL  
3  — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE  
4  It's primary day in New York and front-runners...  REAL

In [ ]:
df.shape

(6335, 4)

In [ ]:
df.isnull().sum()

Unnamed: 0    0
title         0
text          0
label         0
dtype: int64

In [ ]:
tfidf = TfidfVectorizer(max_features=5000)
df['content'] = df['title'] + " " + df['text']

In [ ]:
X=tfidf.fit_transform(df['content'])
y=(df['label'])

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=42)

In [ ]:
model = LogisticRegression()

model.fit(X_train,y_train)

LogisticRegression()

In [ ]:
ypred = model.predict(X_test)
print('confusion matrix\n',confusion_matrix(ypred,y_test),'\n')
print('CLassification report\n',classification_report(ypred,y_test),'\n')
print('Accuracy score', accuracy_score(ypred,y_test))

confusion matrix
 [[905  93]
 [ 63 840]] 

CLassification report
               precision    recall  f1-score   support

        FAKE       0.93      0.91      0.92       998
        REAL       0.90      0.93      0.92       903

    accuracy                           0.92      1901
   macro avg       0.92      0.92      0.92      1901
weighted avg       0.92      0.92      0.92      1901
 

Accuracy score 0.917937927406628


In [ ]:
ypred = model.predict(X_train)
print('confusion matrix\n',confusion_matrix(ypred,y_train),'\n')
print('CLassification report\n',classification_report(ypred,y_train),'\n')
print('Accuracy score', accuracy_score(ypred,y_train))

confusion matrix
 [[2097  136]
 [  99 2102]] 

CLassification report
               precision    recall  f1-score   support

        FAKE       0.95      0.94      0.95      2233
        REAL       0.94      0.96      0.95      2201

    accuracy                           0.95      4434
   macro avg       0.95      0.95      0.95      4434
weighted avg       0.95      0.95      0.95      4434
 

Accuracy score 0.947000451059991


In [ ]:
model = RandomForestClassifier()

model.fit(X_train,y_train)

RandomForestClassifier()

In [ ]:
ypred = model.predict(X_test)
print('confusion matrix\n',confusion_matrix(ypred,y_test),'\n')
print('CLassification report\n',classification_report(ypred,y_test),'\n')
print('Accuracy score', accuracy_score(ypred,y_test))

confusion matrix
 [[897  87]
 [ 71 846]] 

CLassification report
               precision    recall  f1-score   support

        FAKE       0.93      0.91      0.92       984
        REAL       0.91      0.92      0.91       917

    accuracy                           0.92      1901
   macro avg       0.92      0.92      0.92      1901
weighted avg       0.92      0.92      0.92      1901
 

Accuracy score 0.9168858495528669


In [ ]:
model = DecisionTreeClassifier()

model.fit(X_train,y_train)

DecisionTreeClassifier()

In [ ]:
ypred = model.predict(X_test)
print('confusion matrix\n',confusion_matrix(ypred,y_test),'\n')
print('CLassification report\n',classification_report(ypred,y_test),'\n')
print('Accuracy score', accuracy_score(ypred,y_test))     `1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111    `

confusion matrix
 [[769 190]
 [199 743]] 

CLassification report
               precision    recall  f1-score   support

        FAKE       0.79      0.80      0.80       959
        REAL       0.80      0.79      0.79       942

    accuracy                           0.80      1901
   macro avg       0.80      0.80      0.80      1901
weighted avg       0.80      0.80      0.80      1901
 

Accuracy score 0.7953708574434508
